apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-status
  namespace: foobar
  labels:
    environment: development
    env-name: foobar
    platform: linq
data:
  environment.json: |
    {
      "id": "1754320616083",
      "name": "foobar",
      "type": "virtual",
      "environmentType": "development",
      "status": "deploying",
      "creationTime": "2025-08-04T15:16:56.083Z",
      "lastUpdated": "2025-08-04T15:16:56.083Z"
    }
