# Default values for linq-orchestrator
replicaCount: 1

image:
  repository: automata-tech/linq-orchestrator
  pullPolicy: IfNotPresent
  tag: "3.2.1"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

config:
  logLevel: "info"
  environment: "development"
  database:
    host: "postgres"
    port: 5432
    name: "orchestrator"
    user: "postgres"
    password: "postgres"
  
  monitoring:
    enabled: true
    prometheusPort: 9090

healthcheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5